dist: ./bin
builds:
  - binary: hog
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
nfpm:
  description: A tool to test incoming TCP connection limits
  maintainer: Redbubble <domain@redbubble.com>
  formats:
    - deb
    # - rpm
  license: MIT
brew:
  github:
    owner: redbubble
    name: homebrew-hog
  commit_author:
    name: toothbrush
    email: paul@denknerd.org

  folder: Formula
  homepage: https://github.com/redbubble/hog
  description: A tool to test incoming TCP connection limits

  test: |
    system "#{bin}/hog --help"
  install: |
    bin.install "hog"
dockers:
  - binary: hog
    goos: linux
    goarch: amd64
    image_templates:
      - "redbubble/{{ .ProjectName }}:{{ .Tag }}"
      - "redbubble/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "redbubble/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
    skip_push: true
    dockerfile: Dockerfile
